import { COLORS } from "../../theme.js";

export const srmStyle = {
  app: { fontFamily: "'Segoe UI', Arial, sans-serif", fontSize: 13, color: COLORS.text, minHeight: "100vh", display: "flex", flexDirection: "column", background: COLORS.bodyBg },
  header: { background: COLORS.headerBg, color: "#fff", padding: "10px 20px", display: "flex", alignItems: "center", justifyContent: "space-between" },
  headerTitle: { fontWeight: "800", fontSize: 20, letterSpacing: 0.5, color: "#fff", cursor: "pointer" },
  headerRight: { display: "flex", gap: 20, alignItems: "center", fontSize: 13 },
  headerLink: { color: "#cde", cursor: "pointer", textDecoration: "none" },
  headerUser: { display: "flex", alignItems: "center", gap: 6, color: "#cde", cursor: "pointer" },
  subNav: { background: COLORS.subNavBg, display: "flex", alignItems: "center", padding: "0 16px", minHeight: 38, position: "relative", width: "100%", boxSizing: "border-box" },
  subNavNavEnd: { display: "flex", alignItems: "center", marginLeft: "auto" },
  navItem: { color: "#cde", padding: "10px 16px", cursor: "pointer", fontSize: 13, display: "flex", alignItems: "center", gap: 4, userSelect: "none" },
  navItemDisabled: { color: "rgba(205, 222, 238, 0.35)", cursor: "not-allowed", pointerEvents: "none" },
  navItemHover: { background: "rgba(255,255,255,0.08)" },
  dropdown: { position: "absolute", top: 38, left: 0, background: COLORS.dropdownBg, minWidth: 210, zIndex: 100, boxShadow: "2px 4px 12px rgba(0,0,0,0.3)" },
  dropdownItem: { padding: "9px 18px", color: "#d8eef8", cursor: "pointer", borderBottom: "1px solid rgba(255,255,255,0.06)", fontSize: 13 },
  mainLayout: { display: "flex", flex: 1, minHeight: 0 },
  content: { flex: 1, padding: "0 0 0 0", display: "flex", flexDirection: "column", overflow: "auto" },
  pageBar: { background: COLORS.bodyBg, borderBottom: "2px solid #bbd0dc", padding: "10px 18px", display: "flex", alignItems: "center", justifyContent: "space-between" },
  pageTitle: { fontWeight: "600", fontSize: 14, color: COLORS.text },
  pageActions: { display: "flex", gap: 6 },
  btn: { background: COLORS.btnBg, color: "#fff", border: "none", borderRadius: 2, padding: "5px 14px", cursor: "pointer", fontSize: 12, fontWeight: 500 },
  btnOutline: { background: "transparent", color: COLORS.btnBg, border: `1px solid ${COLORS.btnBg}`, borderRadius: 2, padding: "4px 12px", cursor: "pointer", fontSize: 12 },
  contentArea: { padding: "16px 20px", flex: 1 },
  section: { marginBottom: 12 },
  sectionHeader: { display: "flex", alignItems: "center", gap: 8, marginBottom: 10, paddingBottom: 4, borderBottom: `2px solid ${COLORS.sectionLine}` },
  sectionTitle: { fontWeight: "600", fontSize: 13, color: COLORS.text },
  formRow: { display: "flex", alignItems: "center", marginBottom: 8, gap: 0 },
  label: { width: 160, minWidth: 140, fontSize: 12, color: COLORS.text, paddingRight: 10 },
  input: { border: `1px solid ${COLORS.inputBorder}`, borderRadius: 2, padding: "5px 8px", fontSize: 12, width: 280, outline: "none", background: "#fff", boxShadow: "inset 0 1px 2px rgba(0,0,0,0.08)" },
  inputSm: { border: `1px solid ${COLORS.inputBorder}`, borderRadius: 2, padding: "5px 8px", fontSize: 12, width: 160, outline: "none", background: "#fff" },
  select: { border: `1px solid ${COLORS.inputBorder}`, borderRadius: 2, padding: "5px 8px", fontSize: 12, width: 200, background: "#fff", outline: "none" },
  uploadBox: { border: `1px solid ${COLORS.inputBorder}`, width: 180, height: 130, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", cursor: "pointer", background: "#fff", borderRadius: 2 },
  uploadLabel: { color: COLORS.link, fontSize: 12, textDecoration: "underline", marginBottom: 6 },
  uploadSub: { fontSize: 11, color: "#888" },
  table: { width: "100%", borderCollapse: "collapse", fontSize: 12 },
  th: { background: COLORS.tableHeader, color: "#fff", padding: "8px 14px", textAlign: "center", fontWeight: 600 },
  td: { padding: "7px 14px", borderBottom: "1px solid #dce4e8", textAlign: "center", color: COLORS.text, background: "#f0f5f8" },
  sidebar: { width: 230, minWidth: 200, background: "#e0ecf4", borderLeft: "1px solid #c8dbe8", display: "flex", flexDirection: "column", padding: "0" },
  sidePanel: { background: COLORS.sidebarPanelBg, borderBottom: "1px solid #b8cdd8", padding: "10px 14px", minHeight: 80 },
  sidePanelTitle: { fontWeight: "700", fontSize: 13, color: COLORS.text, marginBottom: 6 },
  chargesTable: { width: "100%", borderCollapse: "collapse", fontSize: 12, marginTop: 8 },
  chargesTh: { background: COLORS.tableHeader, color: "#fff", padding: "7px 10px", textAlign: "left", fontWeight: 600 },
  chargesTd: { padding: "6px 10px", borderBottom: "1px solid #dce4e8", background: "#f8fafb" },
  statCard: { background: "#fff", borderRadius: 4, padding: "14px 18px", flex: 1, boxShadow: "0 1px 4px rgba(0,0,0,0.10)", borderLeft: "4px solid " + COLORS.btnBg },
  statVal: { fontSize: 22, fontWeight: "800", color: COLORS.btnBg },
  statLabel: { fontSize: 11, color: "#666", marginTop: 2 },
  badge: { display: "inline-block", background: COLORS.btnBg, color: "#fff", borderRadius: 10, padding: "1px 9px", fontSize: 11 },
  badgeGreen: { display: "inline-block", background: "#2e8a5a", color: "#fff", borderRadius: 10, padding: "1px 9px", fontSize: 11 },
  badgeRed: { display: "inline-block", background: "#c0392b", color: "#fff", borderRadius: 10, padding: "1px 9px", fontSize: 11 },
};
