import { COLORS } from "../theme.js";

export const loginStyle = {
  loginWrap: {
    background: "linear-gradient(135deg, #162d3a 0%, #1e5068 60%, #2e7ea0 100%)",
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
  },
  loginHeader: { padding: "18px 30px" },
  loginTitle: { fontWeight: "900", fontSize: 30, color: "#fff", marginBottom: 4 },
  loginNav: { display: "flex", gap: 30, marginBottom: 10, flexWrap: "wrap" },
  loginNavLink: {
    color: "#cde",
    fontSize: 13,
    cursor: "pointer",
    textDecoration: "underline",
    fontFamily: "Georgia, 'Times New Roman', serif",
  },
  loginBody: { flex: 1, display: "flex", padding: "0 30px 30px 30px", gap: 20, flexWrap: "wrap" },
  loginHero: { flex: 1, display: "flex", alignItems: "center", justifyContent: "center", position: "relative", minWidth: 280 },
  loginHeroBg: {
    width: "100%",
    height: 340,
    background: "linear-gradient(120deg, rgba(30,80,104,0.7) 0%, rgba(46,126,160,0.4) 100%)",
    borderRadius: 6,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    position: "relative",
  },
  loginCard: {
    background: "#fff",
    borderRadius: 14,
    padding: "32px 28px",
    width: 280,
    boxShadow: "0 8px 32px rgba(0,0,0,0.25)",
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },
  loginFieldLabel: { fontSize: 13, color: "#333", marginBottom: 4, fontWeight: 500 },
  loginInput: {
    border: "1.5px solid #aaa",
    borderRadius: 3,
    padding: "8px 10px",
    fontSize: 13,
    width: "100%",
    outline: "none",
    boxSizing: "border-box",
  },
  loginBtn: {
    background: "#135B77",
    color: "#fff",
    border: "none",
    borderRadius: 4,
    padding: "10px",
    fontSize: 14,
    cursor: "pointer",
    fontWeight: 600,
    marginTop: 4,
  },
  loginBtnDisabled: { opacity: 0.65, cursor: "not-allowed" },
  loginLink: {
    color: COLORS.link,
    fontSize: 13,
    textAlign: "center",
    cursor: "pointer",
    textDecoration: "underline",
    fontFamily: "Georgia, 'Times New Roman', serif",
  },
  loginFooter: { textAlign: "center", color: "#a8c8d8", fontSize: 12, padding: "10px 0 16px 0" },
};
